# Generated by Django 5.2 on 2025-05-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_processedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
